name: Q1

on:
  push:
    branches: ['master']

permissions:
  contents: write

jobs:
  archive-readme:
    name: Créer et pousser Q1_archive_README.md
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copier TOTO.txt -> Q1_archive_TOTO.txt
        run: |
          cp TOTO.txt Q1_archive_TOTO.txt

      - name: Commit si changement
        run: |

          # Config auteur du commit
          git config user.name  "Jujedie"
          git config user.email "oyer.ludovic@gmail.com"

          git add Q1_archive_TOTO.txt
          git commit -m "Q1: archive TOTO.md into Q1_archive_TOTO.txt"

      - name: Push
        run: |
          git push